version: "3"
services:
  app:
    build: .
    container_name: clean-arch-back
    ports:
      - "2222:2222"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    container_name: clean-arch-postgres
    environment:
      - PGUSER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=clean_arch
    healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval: 15s
        timeout: 10s
        retries: 10